import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

function getServiceClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key =
    process.env.SUPABASE_SERVICE_ROLE_KEY ||
    process.env.SUPABASE_SERVICE_KEY ||
    process.env.SUPABASE_SERVICE_ROLE;

  if (!url || !key) {
    throw new Error("Missing env: NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");
  }

  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
}

// Optional Resend integration (safe: route can still run even if you haven't wired email yet)
async function sendEmailResend(subject: string, html: string) {
  const apiKey = process.env.RESEND_API_KEY;
  const from = process.env.RESEND_FROM; // e.g. "Baxter ASC <alerts@yourdomain.com>"
  const to = process.env.RESEND_TO;     // comma-separated list

  if (!apiKey || !from || !to) {
    // If not configured, we fail clearly (so you know why emails didn't send)
    throw new Error("Missing RESEND_API_KEY / RESEND_FROM / RESEND_TO env vars");
  }

  const recipients = to.split(",").map((s) => s.trim()).filter(Boolean);

  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      from,
      to: recipients,
      subject,
      html,
    }),
  });

  const json = await res.json().catch(() => ({}));
  if (!res.ok) {
    throw new Error(json?.message || `Resend failed (${res.status})`);
  }

  return json;
}

export async function POST() {
  try {
    const supabase = getServiceClient();

    // Grab up to 25 pending alerts (you can increase later)
    const { data: pending, error: qErr } = await supabase
      .from("low_stock_queue")
      .select("id, created_at, storage_area_id, item_id, on_hand, par_level, low_level")
      .eq("status", "PENDING")
      .order("created_at", { ascending: true })
      .limit(25);

    if (qErr) {
      return NextResponse.json({ ok: false, error: qErr.message }, { status: 500 });
    }

    if (!pending || pending.length === 0) {
      return NextResponse.json({ ok: true, sent: 0, message: "No pending alerts." });
    }

    // Enrich with names using your existing view (best-effort)
    // If you don’t have exact column names, we’ll still send with IDs.
    const areaIds = [...new Set(pending.map((p) => p.storage_area_id))];
    const itemIds = [...new Set(pending.map((p) => p.item_id))];

    const { data: areas } = await supabase
      .from("storage_areas")
      .select("id, name")
      .in("id", areaIds);

    const { data: items } = await supabase
      .from("items")
      .select("id, name, reference_number, vendor")
      .in("id", itemIds);

    const areaMap = new Map((areas || []).map((a: any) => [a.id, a.name]));
    const itemMap = new Map((items || []).map((i: any) => [i.id, i]));

    let sentCount = 0;

    for (const row of pending as any[]) {
      try {
        const areaName = areaMap.get(row.storage_area_id) || row.storage_area_id;
        const it = itemMap.get(row.item_id) || {};
        const itemName = it.name || row.item_id;
        const ref = it.reference_number ? ` (${it.reference_number})` : "";
        const vendor = it.vendor ? ` — ${it.vendor}` : "";

        const subject = `LOW STOCK: ${areaName} — ${itemName}${ref}`;
        const html = `
          <div style="font-family: Arial, sans-serif; line-height: 1.4;">
            <h2>Low Stock Alert</h2>
            <p><b>Location:</b> ${areaName}</p>
            <p><b>Item:</b> ${itemName}${ref}${vendor}</p>
            <p><b>On Hand:</b> ${row.on_hand}</p>
            <p><b>PAR:</b> ${row.par_level}</p>
            <p><b>Low Level:</b> ${row.low_level}</p>
            <p style="color:#666;">Generated by Baxter ASC Inventory</p>
          </div>
        `;

        await sendEmailResend(subject, html);

        // Mark sent
        const { error: uErr } = await supabase
          .from("low_stock_queue")
          .update({ status: "SENT", sent_at: new Date().toISOString(), last_error: null })
          .eq("id", row.id);

        if (uErr) throw new Error(uErr.message);

        sentCount += 1;
      } catch (e: any) {
        // Mark error and bump attempts
        await supabase
          .from("low_stock_queue")
          .update({
            status: "ERROR",
            attempts: (row.attempts || 0) + 1,
            last_error: e?.message || "Unknown send error",
          })
          .eq("id", row.id);
      }
    }

    return NextResponse.json({ ok: true, sent: sentCount, processed: pending.length });
  } catch (e: any) {
    return NextResponse.json(
      { ok: false, error: e?.message || "Server error" },
      { status: 500 }
    );
  }
}
