"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

const supabase = createClient();
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(n)||0);
const monthly=(a:number,f:string)=>f==="weekly"?a*52/12:f==="biweekly"?a*26/12:f==="semimonthly"?a*2:f==="annual"?a/12:f==="one_time"?0:a;

type Tab="Dashboard"|"Wedding"|"Debt"|"Budget"|"Savings"|"Share";
type H={id:string;name:string;invite_code:string};
type I={id:string;name:string;amount:number;frequency:string};
type B={id:string;name:string;category:string;amount:number;due_day:number|null};
type D={id:string;lender:string;balance:number;apr:number;minimum_payment:number};
type W={id:string;item:string;vendor:string|null;total_cost:number;paid_amount:number;due_date:string|null;priority:string;status:string};
type S={id:string;name:string;target_amount:number;current_amount:number};

const css=`
.fin{min-height:100vh;background:#08111f;color:#f8fafc;font-family:Arial,sans-serif}.wrap{max-width:1450px;margin:auto;padding:16px}.head,.card{background:#111c2e;border:1px solid #223551;border-radius:18px}.head{padding:18px;display:flex;justify-content:space-between;gap:16px;align-items:center}.brand{font-weight:900;font-size:25px}.brand span{color:#60a5fa}.muted{color:#93a4bd;font-size:12px}.tabs{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:14px 0}.tab,.btn{border:1px solid #2a3f5f;background:#111c2e;color:#b7c4d8;border-radius:12px;padding:11px;font-weight:800}.tab.on,.btn.primary{background:#2563eb;color:white}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.grid2{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.card{padding:16px;margin-top:12px}.label{font-size:11px;color:#93a4bd;text-transform:uppercase;font-weight:800}.value{font-size:28px;font-weight:900;margin-top:5px}.good{color:#6ee7b7}.warn{color:#fcd34d}.bad{color:#fca5a5}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px 0;border-bottom:1px solid #223551}.row:last-child{border-bottom:0}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:10px}.input{width:100%;background:#0a1423;border:1px solid #2a3f5f;color:white;border-radius:11px;padding:11px}.title{font-weight:900;margin-bottom:10px}.btn{cursor:pointer}.danger{color:#fca5a5}.auth{max-width:520px;margin:10vh auto}.code{font-size:26px;letter-spacing:3px;font-weight:900;color:#93c5fd}.progress{height:10px;background:#0a1423;border-radius:20px;overflow:hidden;margin-top:7px}.progress i{display:block;height:100%;background:#2563eb}.callout{background:#0d2444;border:1px solid #254d7c;padding:13px;border-radius:12px}.empty{color:#93a4bd;border:1px dashed #2a3f5f;border-radius:12px;padding:20px;text-align:center}@media(max-width:900px){.grid4{grid-template-columns:repeat(2,1fr)}.form{grid-template-columns:repeat(2,1fr)}.tabs{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.wrap{padding:10px}.grid4,.grid2,.form{grid-template-columns:1fr}.tabs{position:sticky;top:0;background:#08111f;padding:8px 0;z-index:5}.brand{font-size:20px}}
`;

export default function FinancePage(){
 const [tab,setTab]=useState<Tab>("Dashboard"),[loading,setLoading]=useState(true),[uid,setUid]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState("");
 const [h,setH]=useState<H|null>(null),[income,setIncome]=useState<I[]>([]),[bills,setBills]=useState<B[]>([]),[debts,setDebts]=useState<D[]>([]),[wedding,setWedding]=useState<W[]>([]),[savings,setSavings]=useState<S[]>([]),[weddingDate,setWeddingDate]=useState(""),[joinCode,setJoinCode]=useState("");
 async function load(){setLoading(true);const {data:{user}}=await supabase.auth.getUser();setUid(user?.id||null);if(!user){setLoading(false);return}const {data:m}=await supabase.from("finance_members").select("household_id").limit(1);const hid=m?.[0]?.household_id;if(!hid){setH(null);setLoading(false);return}const [hh,i,b,d,w,s,st]=await Promise.all([supabase.from("finance_households").select("id,name,invite_code").eq("id",hid).single(),supabase.from("finance_income").select("*").eq("household_id",hid),supabase.from("finance_bills").select("*").eq("household_id",hid),supabase.from("finance_debts").select("*").eq("household_id",hid).order("apr",{ascending:false}),supabase.from("finance_wedding_expenses").select("*").eq("household_id",hid).order("due_date"),supabase.from("finance_savings_goals").select("*").eq("household_id",hid),supabase.from("finance_settings").select("wedding_date").eq("household_id",hid).single()]);setH(hh.data as H);setIncome((i.data||[]) as I[]);setBills((b.data||[]) as B[]);setDebts((d.data||[]) as D[]);setWedding((w.data||[]) as W[]);setSavings((s.data||[]) as S[]);setWeddingDate(st.data?.wedding_date||"");setLoading(false)}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!h)return;const c=supabase.channel(`finance-${h.id}`).on("postgres_changes",{event:"*",schema:"public",table:"finance_income",filter:`household_id=eq.${h.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_bills",filter:`household_id=eq.${h.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_debts",filter:`household_id=eq.${h.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_wedding_expenses",filter:`household_id=eq.${h.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_savings_goals",filter:`household_id=eq.${h.id}`},load).subscribe();return()=>{supabase.removeChannel(c)}},[h?.id]);
 const c=useMemo(()=>{const inc=income.reduce((a,x)=>a+monthly(Number(x.amount),x.frequency),0),bill=bills.reduce((a,x)=>a+Number(x.amount),0),mins=debts.reduce((a,x)=>a+Number(x.minimum_payment),0),debt=debts.reduce((a,x)=>a+Number(x.balance),0),wed=wedding.filter(x=>x.status!=="cancelled").reduce((a,x)=>a+Math.max(0,Number(x.total_cost)-Number(x.paid_amount)),0),saved=savings.reduce((a,x)=>a+Number(x.current_amount),0),targets=savings.reduce((a,x)=>a+Number(x.target_amount),0),free=inc-bill-mins;let months=1;if(weddingDate)months=Math.max(1,Math.ceil((new Date(weddingDate).getTime()-Date.now())/(1000*60*60*24*30.44)));const wedMonth=Math.min(Math.max(0,free),wed/months),left=Math.max(0,free-wedMonth),save=Math.min(Math.max(0,targets-saved),left*.35),extra=Math.max(0,(left-save)*.8),safe=Math.max(0,left-save-extra);return{inc,bill,mins,debt,wed,saved,targets,free,months,wedMonth,save,extra,safe}},[income,bills,debts,wedding,savings,weddingDate]);
 async function auth(e:FormEvent,signup:boolean){e.preventDefault();setMsg("");const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setMsg(r.error.message);else load()}
 async function add(table:string,payload:any,form:HTMLFormElement){if(!h)return;const {error}=await supabase.from(table).insert({...payload,household_id:h.id,created_by:uid});if(error)setMsg(error.message);else{form.reset();load()}}
 async function del(table:string,id:string){await supabase.from(table).delete().eq("id",id);load()}
 if(loading)return <div className="fin"><style>{css}</style><div className="wrap"><div className="card">Loading Financial Control Center…</div></div></div>;
 if(!uid)return <div className="fin"><style>{css}</style><div className="wrap auth"><div className="card"><div className="brand">Financial <span>Control Center</span></div><p className="muted">Private live wedding, debt, savings and budget planning.</p><form onSubmit={e=>auth(e,false)}><input className="input" type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="input" style={{marginTop:8}} type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><div style={{display:"flex",gap:8,marginTop:10}}><button className="btn primary">Sign in</button><button type="button" className="btn" onClick={e=>auth(e as any,true)}>Create account</button></div></form>{msg&&<p className="bad">{msg}</p>}</div></div></div>;
 if(!h)return <div className="fin"><style>{css}</style><div className="wrap auth"><div className="card"><div className="brand">Start your plan</div><button className="btn primary" onClick={async()=>{const {error}=await supabase.from("finance_households").insert({name:"My Financial Plan",owner_id:uid});if(error)setMsg(error.message);else load()}}>Create my financial plan</button><div style={{display:"flex",gap:8,marginTop:14}}><input className="input" placeholder="Invite code" value={joinCode} onChange={e=>setJoinCode(e.target.value)}/><button className="btn" onClick={async()=>{const {error}=await supabase.rpc("finance_join_household",{p_invite_code:joinCode});if(error)setMsg(error.message);else load()}}>Join</button></div>{msg&&<p className="bad">{msg}</p>}</div></div></div>;
 const metric=(label:string,value:string,cls="")=><div className="card"><div className="label">{label}</div><div className={`value ${cls}`}>{value}</div></div>;
 return <div className="fin"><style>{css}</style><div className="wrap"><div className="head"><div><div className="brand">Financial <span>Control Center</span></div><div className="muted">{h.name} · live household dashboard</div></div><button className="btn" onClick={()=>supabase.auth.signOut().then(()=>location.reload())}>Sign out</button></div><div className="tabs">{(["Dashboard","Wedding","Debt","Budget","Savings","Share"] as Tab[]).map(x=><button key={x} className={`tab ${tab===x?"on":""}`} onClick={()=>setTab(x)}>{x}</button>)}</div>{msg&&<div className="card bad">{msg}</div>}
 {tab==="Dashboard"&&<><div className="grid4">{metric("Monthly income",money(c.inc),"good")}{metric("Free after bills + minimums",money(c.free),c.free>=0?"good":"bad")}{metric("Wedding still owed",money(c.wed),"warn")}{metric("Total debt",money(c.debt),"bad")}</div><div className="grid4">{metric("Wedding / month",money(c.wedMonth))}{metric("Savings / month",money(c.save))}{metric("Extra debt / month",money(c.extra),"good")}{metric("Safe to spend",money(c.safe),"warn")}</div><div className="grid2"><div className="card"><div className="title">Your monthly plan</div><div className="row"><span>Bills</span><b>{money(c.bill)}</b></div><div className="row"><span>Debt minimums</span><b>{money(c.mins)}</b></div><div className="row"><span>Wedding</span><b>{money(c.wedMonth)}</b></div><div className="row"><span>Savings</span><b>{money(c.save)}</b></div><div className="row"><span>Extra debt</span><b>{money(c.extra)}</b></div><div className="row"><span>Safe to spend</span><b>{money(c.safe)}</b></div></div><div className="card"><div className="title">Goal health</div><div className="callout">Wedding is {c.months} month{c.months===1?"":"s"} away. Bills and minimum debt payments are protected before wedding, savings and extra debt allocations.</div><div style={{marginTop:14}}>Savings {money(c.saved)} / {money(c.targets)}<div className="progress"><i style={{width:`${c.targets?Math.min(100,c.saved/c.targets*100):0}%`}}/></div></div></div></div></>}
 {tab==="Budget"&&<><div className="card"><div className="title">Income</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_income",{name:f.get("name"),amount:Number(f.get("amount")),frequency:f.get("frequency")},e.currentTarget)}}><input className="input" name="name" placeholder="Income" required/><input className="input" name="amount" type="number" step=".01" placeholder="Amount" required/><select className="input" name="frequency"><option value="monthly">Monthly</option><option value="biweekly">Every 2 weeks</option><option value="semimonthly">Twice monthly</option><option value="weekly">Weekly</option><option value="annual">Annual</option></select><button className="btn primary">Add</button></form>{income.map(x=><div className="row" key={x.id}><span><b>{x.name}</b><div className="muted">{x.frequency}</div></span><span>{money(x.amount)} <button className="btn danger" onClick={()=>del("finance_income",x.id)}>×</button></span></div>)}</div><div className="card"><div className="title">Bills</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_bills",{name:f.get("name"),amount:Number(f.get("amount")),category:f.get("category")||"Other",due_day:Number(f.get("due"))||null},e.currentTarget)}}><input className="input" name="name" placeholder="Bill" required/><input className="input" name="amount" type="number" step=".01" placeholder="Amount" required/><input className="input" name="category" placeholder="Category"/><input className="input" name="due" type="number" min="1" max="31" placeholder="Due day"/><button className="btn primary">Add</button></form>{bills.map(x=><div className="row" key={x.id}><span><b>{x.name}</b><div className="muted">{x.category}</div></span><span>{money(x.amount)} <button className="btn danger" onClick={()=>del("finance_bills",x.id)}>×</button></span></div>)}</div></>}
 {tab==="Debt"&&<div className="card"><div className="title">Debt attack center</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_debts",{lender:f.get("lender"),balance:Number(f.get("balance")),apr:Number(f.get("apr"))/100,minimum_payment:Number(f.get("minimum")),extra_payment:0},e.currentTarget)}}><input className="input" name="lender" placeholder="Lender" required/><input className="input" name="balance" type="number" step=".01" placeholder="Balance" required/><input className="input" name="apr" type="number" step=".01" placeholder="APR %" required/><input className="input" name="minimum" type="number" step=".01" placeholder="Minimum" required/><button className="btn primary">Add debt</button></form>{debts.length?debts.map(x=><div className="row" key={x.id}><span><b>{x.lender}</b><div className="muted">{(Number(x.apr)*100).toFixed(2)}% APR · min {money(x.minimum_payment)}</div></span><span>{money(x.balance)} <button className="btn danger" onClick={()=>del("finance_debts",x.id)}>×</button></span></div>):<div className="empty">Add your debts here.</div>}</div>}
 {tab==="Wedding"&&<div className="card"><div className="title">Wedding payment tracker</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_wedding_expenses",{item:f.get("item"),vendor:f.get("vendor"),total_cost:Number(f.get("total")),paid_amount:Number(f.get("paid"))||0,due_date:f.get("due")||null,priority:f.get("priority")||"important"},e.currentTarget)}}><input className="input" name="item" placeholder="Expense" required/><input className="input" name="vendor" placeholder="Vendor"/><input className="input" name="total" type="number" step=".01" placeholder="Total" required/><input className="input" name="paid" type="number" step=".01" placeholder="Paid"/><input className="input" name="due" type="date"/><select className="input" name="priority"><option value="must_pay">Must pay</option><option value="important">Important</option><option value="optional">Optional</option></select><button className="btn primary">Add expense</button></form>{wedding.map(x=><div className="row" key={x.id}><span><b>{x.item}</b><div className="muted">{x.vendor||"No vendor"}{x.due_date?` · due ${x.due_date}`:""}</div></span><span><b>{money(Math.max(0,Number(x.total_cost)-Number(x.paid_amount)))} owed</b> <button className="btn danger" onClick={()=>del("finance_wedding_expenses",x.id)}>×</button></span></div>)}</div>}
 {tab==="Savings"&&<div className="card"><div className="title">Savings goals</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_savings_goals",{name:f.get("name"),target_amount:Number(f.get("target")),current_amount:Number(f.get("current"))||0},e.currentTarget)}}><input className="input" name="name" placeholder="Goal" required/><input className="input" name="target" type="number" step=".01" placeholder="Target" required/><input className="input" name="current" type="number" step=".01" placeholder="Already saved"/><button className="btn primary">Add goal</button></form>{savings.map(x=><div className="row" key={x.id}><span style={{flex:1}}><b>{x.name}</b><div className="progress"><i style={{width:`${x.target_amount?Math.min(100,Number(x.current_amount)/Number(x.target_amount)*100):0}%`}}/></div></span><span>{money(x.current_amount)} / {money(x.target_amount)} <button className="btn danger" onClick={()=>del("finance_savings_goals",x.id)}>×</button></span></div>)}</div>}
 {tab==="Share"&&<div className="grid2"><div className="card"><div className="title">Share this live plan</div><p className="muted">The other person creates an account and joins with this private code.</p><div className="code">{h.invite_code}</div><button className="btn" style={{marginTop:10}} onClick={()=>navigator.clipboard.writeText(h.invite_code)}>Copy code</button></div><div className="card"><div className="title">Wedding date</div><input className="input" type="date" value={weddingDate} onChange={async e=>{setWeddingDate(e.target.value);await supabase.from("finance_settings").update({wedding_date:e.target.value||null}).eq("household_id",h.id)}}/><p className="muted">Your finance data is restricted to authenticated members of this household.</p></div></div>}
 </div></div>
}
