"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Tab = "Dashboard" | "Wedding" | "Debt" | "Budget" | "Savings" | "Share";
type Household = { id:string; name:string; invite_code:string; owner_id:string };
type Income = { id:string; name:string; amount:number; frequency:string; income_date:string|null };
type Bill = { id:string; name:string; category:string; amount:number; due_day:number|null };
type Debt = { id:string; lender:string; balance:number; apr:number; minimum_payment:number; extra_payment:number; due_day:number|null; priority:string };
type Wedding = { id:string; item:string; vendor:string|null; total_cost:number; paid_amount:number; due_date:string|null; priority:string; status:string };
type Saving = { id:string; name:string; target_amount:number; current_amount:number; priority:number };
type Settings = { wedding_date:string|null; cash_on_hand:number; minimum_buffer:number };

const supabase = createClient();
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(n)||0);
const monthly=(amount:number, frequency:string)=> frequency==="weekly"?amount*52/12:frequency==="biweekly"?amount*26/12:frequency==="semimonthly"?amount*2:frequency==="annual"?amount/12:frequency==="one_time"?0:amount;
const css=`
:root{--bg:#080d18;--card:#111a2b;--card2:#162238;--line:#243653;--text:#f3f7ff;--muted:#8ea0bb;--blue:#3b82f6;--green:#10b981;--yellow:#f59e0b;--red:#ef4444;--purple:#8b5cf6}
*{box-sizing:border-box}.fin{min-height:100vh;background:radial-gradient(circle at 15% 0,#172554 0,transparent 28%),var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.wrap{width:100%;max-width:1500px;margin:auto;padding:18px 16px 80px}.head{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:18px;background:linear-gradient(135deg,#172033,#0d1422);border:1px solid var(--line);border-radius:20px}.brand{font-size:24px;font-weight:900;letter-spacing:-.8px}.brand span{color:#60a5fa}.sub,.muted{color:var(--muted);font-size:12px}.tabs{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin:14px 0}.tab,.btn{border:1px solid var(--line);background:var(--card);color:var(--muted);border-radius:12px;padding:11px 10px;font-weight:800;cursor:pointer}.tab.on,.btn.primary{background:var(--blue);border-color:var(--blue);color:white}.grid4{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.card{background:rgba(17,26,43,.96);border:1px solid var(--line);border-radius:18px;padding:16px;margin-top:12px;box-shadow:0 10px 35px rgba(0,0,0,.18)}.metric .label{font-size:11px;text-transform:uppercase;letter-spacing:.7px;color:var(--muted);font-weight:800}.metric .value{font-size:27px;font-weight:950;margin-top:5px}.good{color:#6ee7b7}.warn{color:#fcd34d}.bad{color:#fca5a5}.title{font-size:15px;font-weight:900;margin-bottom:12px}.progress{height:10px;background:#0a1220;border-radius:99px;overflow:hidden;margin-top:8px}.progress>i{display:block;height:100%;background:linear-gradient(90deg,var(--blue),var(--purple));border-radius:99px}.row{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px 0;border-bottom:1px solid #1d2b43}.row:last-child{border:0}.row strong{font-size:13px}.row .right{text-align:right}.form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px}.input{width:100%;background:#0b1321;border:1px solid var(--line);color:white;border-radius:11px;padding:11px;font-size:14px}.input::placeholder{color:#60708a}.sectionActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.btn{padding:10px 14px}.btn.danger{color:#fca5a5}.empty{padding:24px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:14px}.callout{padding:14px;border-radius:14px;background:rgba(59,130,246,.09);border:1px solid rgba(59,130,246,.3);font-size:13px;line-height:1.5}.auth{max-width:520px;margin:9vh auto}.auth h1{font-size:30px;margin:0 0 8px}.auth .card{padding:24px}.code{font-size:24px;font-weight:950;letter-spacing:3px;color:#93c5fd}.pill{display:inline-block;padding:4px 8px;border-radius:99px;background:#17233a;color:#a9b9d0;font-size:10px;font-weight:800;text-transform:uppercase}.split{display:flex;gap:10px}.split>*{flex:1}
@media(max-width:900px){.grid4{grid-template-columns:repeat(2,1fr)}.form{grid-template-columns:repeat(2,1fr)}.tabs{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.wrap{padding:10px 10px 70px}.head{align-items:flex-start}.brand{font-size:20px}.grid4,.grid2,.form{grid-template-columns:1fr}.tabs{position:sticky;top:0;z-index:10;background:rgba(8,13,24,.96);padding:7px 0;grid-template-columns:repeat(3,1fr)}.tab{font-size:11px;padding:9px 5px}.metric .value{font-size:23px}}
`;

export default function FinancePage(){
 const [tab,setTab]=useState<Tab>("Dashboard"),[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState("");
 const [household,setHousehold]=useState<Household|null>(null),[income,setIncome]=useState<Income[]>([]),[bills,setBills]=useState<Bill[]>([]),[debts,setDebts]=useState<Debt[]>([]),[wedding,setWedding]=useState<Wedding[]>([]),[savings,setSavings]=useState<Saving[]>([]),[settings,setSettings]=useState<Settings>({wedding_date:null,cash_on_hand:0,minimum_buffer:1000});
 const [joinCode,setJoinCode]=useState("");
 const load=useCallback(async()=>{setLoading(true);const {data:{user}}=await supabase.auth.getUser();setUserId(user?.id||null);if(!user){setLoading(false);return}const {data:members}=await supabase.from("finance_members").select("household_id").limit(1);let hid=members?.[0]?.household_id;if(!hid){setHousehold(null);setLoading(false);return}const [{data:h},{data:i},{data:b},{data:d},{data:w},{data:s},{data:st}]=await Promise.all([supabase.from("finance_households").select("id,name,invite_code,owner_id").eq("id",hid).single(),supabase.from("finance_income").select("*").eq("household_id",hid).order("created_at"),supabase.from("finance_bills").select("*").eq("household_id",hid).order("due_day"),supabase.from("finance_debts").select("*").eq("household_id",hid).order("apr",{ascending:false}),supabase.from("finance_wedding_expenses").select("*").eq("household_id",hid).order("due_date"),supabase.from("finance_savings_goals").select("*").eq("household_id",hid).order("priority"),supabase.from("finance_settings").select("wedding_date,cash_on_hand,minimum_buffer").eq("household_id",hid).single()]);setHousehold(h as Household);setIncome((i||[]) as Income[]);setBills((b||[]) as Bill[]);setDebts((d||[]) as Debt[]);setWedding((w||[]) as Wedding[]);setSavings((s||[]) as Saving[]);if(st)setSettings(st as Settings);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!household)return;const channel=supabase.channel(`finance-${household.id}`).on("postgres_changes",{event:"*",schema:"public",table:"finance_income",filter:`household_id=eq.${household.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_bills",filter:`household_id=eq.${household.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_debts",filter:`household_id=eq.${household.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_wedding_expenses",filter:`household_id=eq.${household.id}`},load).on("postgres_changes",{event:"*",schema:"public",table:"finance_savings_goals",filter:`household_id=eq.${household.id}`},load).subscribe();return()=>{supabase.removeChannel(channel)}},[household?.id,load]);
 const calc=useMemo(()=>{const inc=income.reduce((a,x)=>a+monthly(Number(x.amount),x.frequency),0),bill=bills.reduce((a,x)=>a+Number(x.amount),0),mins=debts.reduce((a,x)=>a+Number(x.minimum_payment),0),debt=debts.reduce((a,x)=>a+Number(x.balance),0),wed=wedding.filter(x=>x.status!=="cancelled").reduce((a,x)=>a+Math.max(0,Number(x.total_cost)-Number(x.paid_amount)),0),saved=savings.reduce((a,x)=>a+Number(x.current_amount),0),targets=savings.reduce((a,x)=>a+Number(x.target_amount),0),free=inc-bill-mins;let months=1;if(settings.wedding_date){months=Math.max(1,Math.ceil((new Date(settings.wedding_date).getTime()-Date.now())/(1000*60*60*24*30.44)))}const wedMonthly=Math.min(Math.max(0,free),wed/months),afterWed=Math.max(0,free-wedMonthly),saveGap=Math.max(0,targets-saved),saveMonthly=Math.min(saveGap,afterWed*.35),extraDebt=Math.max(0,(afterWed-saveMonthly)*.8),safe=Math.max(0,afterWed-saveMonthly-extraDebt);return{inc,bill,mins,debt,wed,saved,targets,free,months,wedMonthly,saveMonthly,extraDebt,safe}},[income,bills,debts,wedding,savings,settings]);
 async function auth(e:FormEvent,signup=false){e.preventDefault();setMessage("");const r=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(r.error)setMessage(r.error.message);else load()}
 async function createHousehold(){if(!userId)return;const {error}=await supabase.from("finance_households").insert({name:"My Financial Plan",owner_id:userId});if(error)setMessage(error.message);else load()}
 async function join(){const {error}=await supabase.rpc("finance_join_household",{p_invite_code:joinCode});if(error)setMessage(error.message);else load()}
 async function add(table:string,payload:Record<string,unknown>,form:HTMLFormElement){if(!household)return;const {error}=await supabase.from(table).insert({...payload,household_id:household.id,created_by:userId});if(error)setMessage(error.message);else{form.reset();load()}}
 async function del(table:string,id:string){if(!confirm("Delete this item?"))return;await supabase.from(table).delete().eq("id",id);load()}
 if(loading)return <div className="fin"><style>{css}</style><div className="wrap"><div className="card">Loading your financial control center…</div></div></div>;
 if(!userId)return <div className="fin"><style>{css}</style><div className="wrap auth"><div className="card"><h1>Financial Control Center</h1><p className="muted">Private, live budgeting for wedding + debt + savings.</p><form onSubmit={e=>auth(e,false)}><input className="input" placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input className="input" style={{marginTop:8}} placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><div className="split" style={{marginTop:10}}><button className="btn primary">Sign in</button><button type="button" className="btn" onClick={e=>auth(e as any,true)}>Create account</button></div></form>{message&&<p className="bad">{message}</p>}</div></div></div>;
 if(!household)return <div className="fin"><style>{css}</style><div className="wrap auth"><div className="card"><h1>Start your plan</h1><p className="muted">Create a new private household or join one someone shared with you.</p><button className="btn primary" onClick={createHousehold}>Create my financial plan</button><div className="split" style={{marginTop:16}}><input className="input" placeholder="Invite code" value={joinCode} onChange={e=>setJoinCode(e.target.value)}/><button className="btn" onClick={join}>Join</button></div>{message&&<p className="bad">{message}</p>}</div></div></div>;
 const metric=(label:string,value:string,cls="")=><div className="card metric"><div className="label">{label}</div><div className={`value ${cls}`}>{value}</div></div>;
 return <div className="fin"><style>{css}</style><div className="wrap"><header className="head"><div><div className="brand">Financial <span>Control Center</span></div><div className="sub">{household.name} · live household money dashboard</div></div><button className="btn" onClick={()=>supabase.auth.signOut().then(()=>location.reload())}>Sign out</button></header><nav className="tabs">{(["Dashboard","Wedding","Debt","Budget","Savings","Share"] as Tab[]).map(t=><button key={t} className={`tab ${tab===t?"on":""}`} onClick={()=>setTab(t)}>{t}</button>)}</nav>{message&&<div className="card bad">{message}</div>}
 {tab==="Dashboard"&&<><div className="grid4">{metric("Monthly income",money(calc.inc),"good")}{metric("Free after bills + minimums",money(calc.free),calc.free>=0?"good":"bad")}{metric("Wedding still owed",money(calc.wed),"warn")}{metric("Total debt",money(calc.debt),"bad")}</div><div className="grid4">{metric("Wedding / month",money(calc.wedMonthly))}{metric("Savings / month",money(calc.saveMonthly))}{metric("Extra debt / month",money(calc.extraDebt),"good")}{metric("Safe to spend",money(calc.safe),"warn")}</div><div className="grid2"><div className="card"><div className="title">Your money plan right now</div><div className="row"><span>Bills</span><strong>{money(calc.bill)}</strong></div><div className="row"><span>Debt minimums</span><strong>{money(calc.mins)}</strong></div><div className="row"><span>Wedding funding</span><strong>{money(calc.wedMonthly)}</strong></div><div className="row"><span>Savings</span><strong>{money(calc.saveMonthly)}</strong></div><div className="row"><span>Extra debt attack</span><strong>{money(calc.extraDebt)}</strong></div><div className="row"><span>Flexible / safe spend</span><strong>{money(calc.safe)}</strong></div></div><div className="card"><div className="title">Goal health</div><div className="callout">Wedding is {calc.months} month{calc.months===1?"":"s"} away. This planner protects normal bills and minimum debt payments before assigning money to the wedding, savings, and extra debt.</div><div style={{marginTop:16}}><strong>Savings progress · {money(calc.saved)} / {money(calc.targets)}</strong><div className="progress"><i style={{width:`${calc.targets?Math.min(100,calc.saved/calc.targets*100):0}%`}}/></div></div></div></div></>}
 {tab==="Budget"&&<><div className="card"><div className="title">Income</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_income",{name:f.get("name"),amount:Number(f.get("amount")),frequency:f.get("frequency")},e.currentTarget)}}><input name="name" className="input" placeholder="Paycheck / income" required/><input name="amount" className="input" type="number" step=".01" placeholder="Amount" required/><select name="frequency" className="input"><option value="monthly">Monthly</option><option value="biweekly">Every 2 weeks</option><option value="semimonthly">Twice monthly</option><option value="weekly">Weekly</option><option value="annual">Annual</option></select><button className="btn primary">Add income</button></form>{income.map(x=><div className="row" key={x.id}><div><strong>{x.name}</strong><div className="muted">{x.frequency}</div></div><div className="right"><strong>{money(x.amount)}</strong> <button className="btn danger" onClick={()=>del("finance_income",x.id)}>×</button></div></div>)}</div><div className="card"><div className="title">Monthly bills</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_bills",{name:f.get("name"),amount:Number(f.get("amount")),category:f.get("category"),due_day:Number(f.get("due_day"))||null},e.currentTarget)}}><input name="name" className="input" placeholder="Bill" required/><input name="amount" className="input" type="number" step=".01" placeholder="Amount" required/><input name="category" className="input" placeholder="Category"/><input name="due_day" className="input" type="number" min="1" max="31" placeholder="Due day"/><button className="btn primary">Add bill</button></form>{bills.map(x=><div className="row" key={x.id}><div><strong>{x.name}</strong><div className="muted">{x.category}{x.due_day?` · due ${x.due_day}`:""}</div></div><div className="right"><strong>{money(x.amount)}</strong> <button className="btn danger" onClick={()=>del("finance_bills",x.id)}>×</button></div></div>)}</div></>}
 {tab==="Debt"&&<div className="card"><div className="title">Debt attack center</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_debts",{lender:f.get("lender"),balance:Number(f.get("balance")),apr:Number(f.get("apr"))/100,minimum_payment:Number(f.get("minimum")),extra_payment:0},e.currentTarget)}}><input name="lender" className="input" placeholder="Lender / debt" required/><input name="balance" className="input" type="number" step=".01" placeholder="Balance" required/><input name="apr" className="input" type="number" step=".01" placeholder="APR %" required/><input name="minimum" className="input" type="number" step=".01" placeholder="Minimum payment" required/><button className="btn primary">Add debt</button></form>{debts.length?debts.map(x=><div className="row" key={x.id}><div><strong>{x.lender}</strong><div className="muted">{(Number(x.apr)*100).toFixed(2)}% APR · min {money(x.minimum_payment)}</div></div><div className="right"><strong>{money(x.balance)}</strong> <button className="btn danger" onClick={()=>del("finance_debts",x.id)}>×</button></div></div>):<div className="empty">Add your debts and the dashboard will calculate the attack money available.</div>}</div>}
 {tab==="Wedding"&&<div className="card"><div className="title">Wedding payment tracker</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_wedding_expenses",{item:f.get("item"),vendor:f.get("vendor"),total_cost:Number(f.get("total")),paid_amount:Number(f.get("paid"))||0,due_date:f.get("due")||null,priority:f.get("priority")},e.currentTarget)}}><input name="item" className="input" placeholder="Expense / item" required/><input name="vendor" className="input" placeholder="Vendor"/><input name="total" className="input" type="number" step=".01" placeholder="Total cost" required/><input name="paid" className="input" type="number" step=".01" placeholder="Already paid"/><input name="due" className="input" type="date"/><select name="priority" className="input"><option value="must_pay">Must pay</option><option value="important">Important</option><option value="optional">Optional</option></select><button className="btn primary">Add expense</button></form>{wedding.length?wedding.map(x=>{const owed=Math.max(0,Number(x.total_cost)-Number(x.paid_amount));return <div className="row" key={x.id}><div><strong>{x.item}</strong><div className="muted">{x.vendor||"No vendor"}{x.due_date?` · due ${x.due_date}`:""} · <span className="pill">{x.priority.replace("_"," ")}</span></div></div><div className="right"><strong>{money(owed)} owed</strong><div className="muted">{money(x.paid_amount)} paid of {money(x.total_cost)}</div><button className="btn danger" onClick={()=>del("finance_wedding_expenses",x.id)}>Delete</button></div></div>}):<div className="empty">Add every remaining wedding cost here. Your dashboard will tell you how much needs funded each month.</div>}</div>}
 {tab==="Savings"&&<div className="card"><div className="title">Savings goals</div><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);add("finance_savings_goals",{name:f.get("name"),target_amount:Number(f.get("target")),current_amount:Number(f.get("current"))||0},e.currentTarget)}}><input name="name" className="input" placeholder="Goal name" required/><input name="target" className="input" type="number" step=".01" placeholder="Target" required/><input name="current" className="input" type="number" step=".01" placeholder="Already saved"/><button className="btn primary">Add goal</button></form>{savings.map(x=>{const p=x.target_amount?Math.min(100,Number(x.current_amount)/Number(x.target_amount)*100):0;return <div className="row" key={x.id}><div style={{flex:1}}><strong>{x.name}</strong><div className="progress"><i style={{width:`${p}%`}}/></div><div className="muted">{p.toFixed(0)}% complete</div></div><div className="right"><strong>{money(x.current_amount)} / {money(x.target_amount)}</strong> <button className="btn danger" onClick={()=>del("finance_savings_goals",x.id)}>×</button></div></div>})}</div>}
 {tab==="Share"&&<div className="grid2"><div className="card"><div className="title">Share with your household</div><p className="muted">The other person creates an account, opens this page, and enters this private invite code. They will see the same live plan.</p><div className="code">{household.invite_code}</div><button className="btn" style={{marginTop:12}} onClick={()=>navigator.clipboard.writeText(household.invite_code)}>Copy code</button></div><div className="card"><div className="title">Wedding settings</div><label className="muted">Wedding date</label><input className="input" type="date" value={settings.wedding_date||""} onChange={async e=>{const next={...settings,wedding_date:e.target.value||null};setSettings(next);await supabase.from("finance_settings").update({wedding_date:next.wedding_date}).eq("household_id",household.id)}}/><div className="callout" style={{marginTop:12}}>Financial information is restricted by household membership in the database. Do not post your invite code publicly.</div></div></div>}
 </div></div>
}
